language: android
dist: trusty
sudo: required
jdk:
  - openjdk11
android:
  components:
    - tools
    - build-tools-31.0.3
    - android-31
before_script:
  - curl https://kaltura.github.io/fe-tools/android/license.sh | sh
script:
  - ./gradlew googlecast:build
after_failure:
  - cat googlecast/build/reports/lint-results.xml
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
      - gourav.saxena@kaltura.com
    on_success: always
    on_failure: always
