language: android
dist: trusty
sudo: required
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - extra-google-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
script:
  - ./gradlew googlecast:build
after_failure:
  - cat googlecast/build/reports/lint-results.xml
after_success:
  - ./travis-push-to-bintray.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
      - Anton.Afanasiev@kaltura.com
    on_success: always
    on_failure: always

