apply plugin: 'com.android.library'
apply from: 'version.gradle'

android {
    namespace 'com.kaltura.playkit.plugins.googlecast'
    compileSdk 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName libVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField("String","VERSION_NAME","\"${libVersion}\"")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig = true
    }
    publishing {
        publishing {
            singleVariant('release') {
            }
        }
    }
}
 
tasks.withType(Javadoc) {
    options.addBooleanOption('Xdoclint:none', true)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Google Cast

    api ('com.google.android.gms:play-services-cast-framework:21.3.0')/* {
        exclude group: 'com.android.support', module: 'support-v4'
    }*/
    api 'com.google.android.datatransport:transport-api:3.0.0'
    api 'androidx.mediarouter:mediarouter:1.2.6'

    //Gson
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'androidx.appcompat:appcompat:1.4.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.4.0'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}


repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

if (!ext.libVersion.contains('dev')) {
    apply from: './gradle-mvn-push.gradle'
} else {
    apply from: './gradle-mvn-local.gradle'
}

